FROM python:3.12-slim

WORKDIR /app

# Copiar código y script de entrada
COPY . .
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Instalar dependencias
RUN pip install --upgrade pip && pip install -r requirements.txt

# Exponer el puerto
EXPOSE 5000

# Usar el script como punto de entrada
ENTRYPOINT ["/entrypoint.sh"]
